version: '3.2'

networks:
  nat:
    external: true
  internal:
    external: false

networks:
  nat:
    external: true
  internal:
    external: false
    ipam:
      config:
        - subnet: 172.31.0.0/16

services:

  # should not be exposed to outside world; replication should go from master to slave!
  couchdb:
    image: apache/couchdb:2.3.1
    restart: always
    ports:
      - 5984:5984 # shield this with Firewall for Administrative IP range only!
    networks:
      - nat
      - internal
    env_file: .env
    environment:
      - COUCHDB_USER=${COUCHDB_ADMIN}
      - COUCHDB_PASSWORD=${COUCHDB_PASS}
      - NODENAME=${NODENAME}
    volumes:
      - /mnt/data/couchdb:/var/lib/couchdb
      - /mnt/data/couchdb:/opt/couchdb/data
    networks:
      nat:
      internal:
